[platformio]
default_envs = STM32F103RE_creality_maple

[env:STM32F103RE_creality_maple]
platform = ststm32
board = genericSTM32F103RE
framework = arduino
build_flags =
  -DSTM32F1xx
  -DMCU_STM32F103xE

[env:STM32F103RET6_creality]
platform = ststm32
board = genericSTM32F103RE
framework = arduino
build_flags =
  -DSTM32F1xx
  -DMCU_STM32F103xE
