name: Build Firmware

on:
  workflow_dispatch:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug folder structure
      run: |
        echo "PWD = $(pwd)"
        ls -R .

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install PlatformIO
      run: pip install platformio

    - name: Build Marlin
      run: |
        echo "PWD: $(pwd)"
        cat platformio.ini || echo "platformio.ini NOT FOUND!"
        platformio run -e STM32F103RET_creality
