name: Build Marlin Firmware (GD32F303RET6)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Build Firmware
        run: |
          platformio run -e STM32F103RE_creality

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: marlin-gd32-firmware
          path: |
            .pio/build/STM32F103RE_creality/firmware.bin
            .pio/build/STM32F103RE_creality/firmware.elf
            .pio/build/STM32F103RE_creality/firmware.map
          if-no-files-found: warn
